ProyectoTao/Models/ErrorViewModel.cs
namespace ProyectoTao.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProyectoTao/Models/TipoCliente.cs
using System.ComponentModel.DataAnnotations;
using System.Runtime.CompilerServices;

namespace ProyectoTao.Models
{
    public class TipoCliente
    {


        [Required(ErrorMessage = "El campo {0} es requerido")]
        [StringLength(maximumLength: 50, MinimumLength = 3, ErrorMessage = "La longitud del campo {0} debe estar entre {2} y {1}")]
        [Display(Name = "ID del cliente")]

        public string IDCliente { get; set; }


        [Required(ErrorMessage = "El campo {0} es requerido")]

        [Range(minimum:10, maximum:130, ErrorMessage = "El campo debe ser una Clave valida")]
        [Display(Name = "Clave del cliente")]
        public int ClaveCliente { get; set; }

        [Display(Name = "Nombre del cliente")]
        [StringLength(maximumLength: 50, MinimumLength = 3, ErrorMessage = "La longitud del campo {0} debe estar entre {2} y {1}")]
        public string NombreCliente { get; set; }


        [Display(Name = "Fecha de alta")]
        public DateTime FechaAlta { get; set; }


        [Display(Name = "Tiempo de inactividad")]
        public string TiempoInactivo { get; set; }

        
        public bool Estatus { get; set; }


        


    }
}

ProyectoTao/Controllers/HomeController.cs
using ProyectoTao.Models;
using Microsoft.AspNetCore.Mvc;

using System.Diagnostics;

namespace ProyectoTao.Controllers { 

    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProyectoTao/Controllers/TiposClientesController.cs
using ProyectoTao.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Dapper;

namespace ProyectoTao.Controllers
{


    public class TiposClientesController : Controller
    {
        private readonly string connectionString;

        public TiposClientesController(IConfiguration configuration)
        {
            connectionString = configuration.GetConnectionString("DefaultConnection");
        }

        public IActionResult Crear()
        {
            using (var connection = new SqlConnection(connectionString))
            {
                var query = connection.Query("SELECT 1").FirstOrDefault();
            }

            return View();
        }
    }


    [HttpPost]
        public IActionResult Crear(TipoCliente tipoCliente) 
        {
            if (!ModelState.IsValid)
            {
                return View(tipoCliente);
            }
            return View();
        }



    }
}

ProyectoTao/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProyectoTao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoTao</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoTao.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoTao</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProyectoTao - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProyectoTao/Views/TiposClientes/Crear.cshtml
@model TipoCliente

@{
    ViewData["Title"] = "Crear Cliente";

}

<h1>Registro Cliente TAO</h1>
<h5>Para registrarte, completa los siguientes datos</h5>


<div asp-validation-summary="All" class="text-danger"></div>

<form asp-controller="TiposClientes" asp-action="Crear">
    <div class="mb-3'" >
        <label asp-for="IDCliente" class="form-label"></label>
        <input type="text" asp-for="IDCliente" class="form-control">
       <span asp-validation-for="IDCliente" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="ClaveCliente" class="form-label"></label>
        <input asp-for="ClaveCliente" class="form-control" />
        <span asp-validation-for="ClaveCliente" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="NombreCliente" class="form-label"></label>
        <input asp-for="NombreCliente" class="form-control" />
        <span asp-validation-for="NombreCliente" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="FechaAlta" class="form-label"></label>
        <input asp-for="FechaAlta" class="form-control" />
        <span asp-validation-for="FechaAlta" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="TiempoInactivo" class="form-label"></label>
        <input asp-for="TiempoInactivo" class="form-control" />
        <span asp-validation-for="TiempoInactivo" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Estatus" class="form-label"></label>
        <input asp-for="Estatus" class="form-control" />
        <span asp-validation-for="Estatus" class="text-danger"></span>
    </div>

  

        <button type="submit" class="btn btn-primary col-md-2">Aceptar</button>
</form>

@section  Scripts {
    <partial name="_ValidationScriptsPartial" />

}